### ISSUE TITLE
UpStream Client Users can never login to the admin area for projects

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#147]
We recommend the Members plugin for editing permissions in UpStream:
https://wordpress.org/plugins/members/

One user wanted to allow UpStream Client Users to login to the admin and see projects. However, it seems that projects can never be made visible to clients in the admin, even if they are part of the project.

Can we make this more flexible? Perhaps add another permission that Members can expose?

If someone is a Client User, this is all they can ever see in the admin ...

![screen shot 2017-08-27 at 5 20 46 pm](https://user-images.githubusercontent.com/26938537/29754065-253d1a90-8b4c-11e7-873d-5c915b02bdc4.png)

**Comment by upstreamplugin** [comment]
There's definitely issues in whether the permissions are exposed

Here's how permissions look when exposed by a plugin:
https://upstreamplugin.com/docs/customizing-permissions-upstream/

Here are the developer instructions: https://upstreamplugin.com/docs/permissions-capabilities/

We're not exposing a lot of permissions, whether it's logging into the admin, editing bugs / milestones / discussions, and more.

**Comment by upstreamplugin** [comment]
Confirmed with a 3rd user ... the "UpStream Client User" role is not customizable. Maybe some hard-coded permissions?

**Comment by upstreamplugin** [comment]
a 4th user ... "Can i add capabilities "edit_title_project"" for users"?

**Comment by awijasa** [comment]
Hello,

Just want to drop a note that I commented out these lines on upstream.php to set the Upstream Client User free:

add_filter('admin_init', array($this, 'limitClientUsersAdminAccess'));
add_filter('admin_head', array($this, 'limitClientUsersMenu'));
add_action('admin_bar_menu', array($this, 'limitClientUsersToolbarItems'), 999);

The filters and action above may make turn some users away from the Upstream Client User role because it gives the impression that this role is very limited and inflexible. Commenting them out will make the Upstream Client Role more flexible and editable through another plugin like Members by Justin Tadlock.

Thanks,

Adrian

**Comment by upstreamplugin** [comment]
Many thanks @awijasa 

@deenison One more customer request for this change, please. A customer wanted to allow Client Users to publish milestones.

**Comment by deenison** [comment]
Partially fixed on [v1.12.2](https://github.com/upstreamplugin/UpStream/releases/tag/v1.12.2).

**Comment by deenison** [comment]
Related to #43.
