### ISSUE TITLE
Link Statuses and Completion percentages

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#194]
Would it make sense to allow users to set a completion percentage for each status?

For example, set a project to "Completed" and the task automatically goes to "100%"

**Comment by deenison** [comment]
I think it does. Users would end up having their statuses & percentages more consistent and less prone to errors perhaps.

**Comment by upstreamplugin** [comment]
@deenison Thanks. Yes, sounds a feature we should add.

**Comment by tardis221** [comment]
I too wondered about this and would love to see it added.

**Comment by upstreamplugin** [comment]
One more request for this from a customer:
"On the Proejcts tab, how do I change the completion
percentage? I would think when the associated tasks are complete, the
project percentage would change, but on my trail version it did not. Please
advise"

**Comment by stevejburge** [comment]
One related request:

> I guess there's no way to automatically change a status based on the due date? Like if the task is past due set the status to overdue so it shows up in red when I look at the task list. See the screenshot below.

**Comment by stevejburge** [comment]
One more from a user:

> Task's status should be automatically updated to "Completed" once the progress is set to 100%, and vice versa (if the status is set to complete, the progress should be updated to 100%, otherwise, once the status is set to "Completed" without the progress being updated to 100%, the task disappears from list, and the overall progress was not updated).

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
When you have some spare time, please check my screenshot for me.
![image](https://user-images.githubusercontent.com/39214560/59955110-da5f0900-94ba-11e9-982d-bdc02dd89969.png)
Is it ok?

**Comment by stevejburge** [comment]
@sergeidevstar001 Yes, on the right track

I think the best solution is to have a setting in the admin:

In Progress = 50%
Completed = 100%
New Status = 75%

**Comment by sergeidevstar001** [comment]
Fixed

**Comment by andergmartins** [comment]
@sergeidevstar001 it didn't work on my side. Please, could you double check? If there is any change, please, create a new branch and send a new pull request.

**Comment by sergeidevstar001** [comment]
I got it, I will fix it.
I thought it's only for admin panel.

**Comment by sergeidevstar001** [comment]
Fixed.

**Comment by andergmartins** [comment]
@sergeidevstar001 sorry but a small bug. Please, could you double check?.

Considering my settings:

* In Progress = 5%
* Overdue = 0% (because there is no empty option)
* Completed = 100%
* Closed = 0% (same as Overdue)

It is working well to set to "In Progress" and update the progress to 5%. But there is an issue we need to fix:

If the task is In Progress, the percentage is 5%, if I update to 40% it saves ok. But if I change the status to Overdue, it changes progress to 0% (because that is the setting) and it should do nothing, otherwise it is erasing a valuable information.

Maybe add a new option in the percentage fields with an empty value? And ignore when the value is empty? The 0% must be there and behave the way it is doing now. Just need an empty option to make clear what status don't update the progress field.
