### ISSUE TITLE
Frontend Overview counts are incorrect

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#197]
A big thanks to @awijasa for this ...

On the frontend, the overview counts are incorrect.

We need to fix this file in several places ... /templates/single-project/overview.php:

**FIX 1**

Replace:

$milestones = get_post_meta($project_id, '_upstream_project_milestones');
$milestones = !empty($milestones) ? (array)$milestones[0] : array();

if (isset($milestones[0])) {
$milestones = (array)$milestones[0];
}

With:

$milestones = upstream_project_milestones( $project_id );

**FIX 2**

Add: ( float )$milestone['progress'] < 100 &&
Before: isset($milestone['end_date']) &&

**FIX 3**

Replace:

$tasks = get_post_meta($project_id, '_upstream_project_tasks');
$tasks = !empty($tasks) ? (array)$tasks[0] : array();

if (isset($tasks[0])) {
$tasks = (array)$tasks[0];
}

With:

$tasks = upstream_project_tasks( $project_id );

**FIX 4**

Add: $tasksMap[$task['status']] != 'closed' &&
Before: isset($task['end_date']) &&

**FIX 5**

Replace:

$bugs = get_post_meta($project_id, '_upstream_project_bugs');
$bugs = !empty($bugs) ? (array)$bugs[0] : array();

if (isset($bugs[0])) {
$bugs = (array)$bugs[0];
}

With:

$bugs = upstream_project_bugs( $project_id );

**FIX 6**

Add: $bugsMap[$bug['status']] != 'closed' &&
Before: isset($bug['due_date']) &&

**Comment by deenison** [comment]
Thanks @awijasa. 
This issue was already fixed on [v1.12.2](https://github.com/upstreamplugin/UpStream/releases/tag/v1.12.2) that will be shipped very soon.

**Comment by awijasa** [comment]
Thanks @deenison!!

**Comment by awijasa** [comment]
Hello @deenison and @upstreamplugin,

I see that most of the problems related to this issue have been fixed in 1.12.2. However, there are still a few remaining problems. The frontend overview still considers these with past End Dates as Overdue:

1. Milestones with 100% progress
2. Tasks with Completed/Closed statuses
3. Bugs with Completed/Closed statuses

Workaround:

Add: ( float )$milestone['progress'] < 100 &&
Before: isset($milestone['end_date']) &&

Add: $tasksMap[$task['status']] != 'closed' &&
Before: isset($task['end_date']) &&

Add: $bugsMap[$bug['status']] != 'closed' &&
Before: isset($bug['due_date']) &&

Thanks,

@awijasa

**Comment by upstreamplugin** [comment]
Thanks @awijasa. I'm re-opening this
