### ISSUE TITLE
Remove or improve the comments feature for projects

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#252]
Since the "Comments" update, the original "Discussion area is a bit lost. There is no link to it in the left menu:

![screen shot 2017-12-07 at 4 02 55 pm](https://user-images.githubusercontent.com/26938537/33738715-32e0f326-db68-11e7-904b-72f393d34a38.png)

Here it is, hiding at the bottom of the page with the confusing name "Comments". My reaction was "Comment on what? why?"

![screen shot 2017-12-07 at 4 02 51 pm](https://user-images.githubusercontent.com/26938537/33738741-4ab6e94c-db68-11e7-8162-462dd66b97d5.png)

What should we do with this area? Remove it? Improve it?

**Comment by awijasa** [comment]
Hello @upstreamplugin and @deenison,

Just pitching in my 2 cents. Personally, I don't see this as a UX problem. The UX design for Comments passes my QA radar 👍  especially with Upstream Frontend Edit installed.

UX is subjective. Even designs by Apple are getting a lot of complaints. I'd say that you should spend your time on something else rather than redesigning comments. Maybe it just takes a little bit for the user to get used to the new Comment interface. You may need to hand hold a few customers. It's already much much better than the old Discussion section.

Thanks,

@awijasa

**Comment by stevejburge** [comment]
@awijasa Thanks. Perhaps is might be enough to add a left menu link and change the name to "Project Discussion"?

**Comment by awijasa** [comment]
Hello @stevejburge,

Those two are good ideas from my point of view!

Thanks,

@awijasa

**Comment by deenison** [comment]
I have to agree with you both, those are valid points. 
No idea why the sidebar link disappeared, but it would be good to have it back for consistency. 
I think getting rid of the "Project Discussion/Comments" may not be a good idea because there are already users using it and there might be more in the future.
But +1 for renaming it to a more clear/descriptive name.
