### ISSUE TITLE
Are TinyMCE files loading multiple times?

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#261]
I wonder if this is a possible issue on the frontend?

Lots of scripts for the TinyMCE editor seem to load multiple times, perhaps for each TinyMCE area in UpStream:

![screen_shot_2017-12-12_at_1 45 13_pm_480](https://user-images.githubusercontent.com/26938537/33902577-6e74b0a6-df43-11e7-8644-e3ac51aedc88.png)
![screen_shot_2017-12-12_at_1 45 48_pm_480](https://user-images.githubusercontent.com/26938537/33902578-6ea448b6-df43-11e7-8fa0-4ffc4c91b7bf.png)

**Comment by awijasa** [comment]
Hello @upstreamplugin and @deenison,

I think this is normal behavior. TinyMCE is loading the scripts for the multiple plugins it has: charmap, colorpicker, lists, media, etc. If you hover on the plugin.min.js?... line, you'll see more details about the plugin it is trying to load.

Thanks,

@awijasa

**Comment by stevejburge** [comment]
Thanks @awijasa. We've been trying everything to speed up UpStream. I had wondered if we could load the TinyMCE files once and re-use as needed.

**Comment by awijasa** [comment]
Got it @stevejburge! As it happens, I am also optimizing Upstream on wp-admin for a project that has more than 100 tasks.

I thought that it would be ok to load all the TinyMCE plugins, but they are humongous and slow to load. To reduce the number of plugin.min.js, I did:

On /upstream/includes/up-general-functions.php:
$pluginsToBeAdded only needs these plugins:
wpautoresize
wpgallery
wpdialogs
wpview

You may use [Advanced TinyMCE Configuration](https://wordpress.org/plugins/advanced-tinymce-configuration/) to reduce the number of TinyMCE plugins being loaded by default.

Are you and @deenison comfortable with the idea of modifying the CMB2 library? There are a number of speed optimizations that can be done through CMB2 library mods.

Thanks,

@awijasa

**Comment by stevejburge** [comment]
I'll CC @deenison as his opinions count more than mine on this.

**Comment by deenison** [comment]
Sorry for being late here ~ @stevejburge, @upstreamplugin 

Hey @awijasa, thanks for getting involved.
- - -
About the ton of scripts, awijasa is right. It is just TinyMCE loading all plugins WP thinks it should use/load. Since they're all separated into files, maybe an interesting solution for loading everything at once would be using a JS module loader, like [RequireJS](http://requirejs.org), but all those required scripts would have to be adapted for it I'm afraid, considering how they are atm. Not sure the possible drawbacks of "overwriting" them or amount of work or if it would be worth it or the best approach if that would be the case yet. 

About the optimizations - that's cool! 
Once you're done feel free to send out a pull request. Who knows, some of those changes could get merged into the core someday and benefit other users as well. We can always use great enhancements and ideas.

There's **a lot** (seriously, a lot, as you may have seen already) of room for improvements on UpStream in that matter.
Some would require a relatively small amount of work to be implemented, as others have the potential to be a pandora's box. As such they'll be (and are) implemented carefully over time.

I'm a huge fan of making things better and definitely agree 100% with you sayng that CMB2 could be as well optimized and make it even more flexible than it already is. 
By changing it you mean literally changing the core? If so, I believe it should be considered only as a last resort here though (things can get pretty messy on updates, ie), and only if it CMB2 was to be forked and later get the changes submitted to its original repo.

At this point, it would be better to get done whatever we can within UpStream's scope first rather than change a tool being used by it.

**Comment by awijasa** [comment]
Hi @deenison and @upstreamplugin,

Sorry for replying late after one month... It's been a busy month indeed for me. I'm sure it's even busier for the UpStream team!

I agree with @deenison about modifiying CMB2. That should be a last resort.

Just a heads up: I'm going to submit a few pull requests that may optimize the speed of some activities in a Project on wp-admin. However, some of them favor speed over functionalities. For example, I don't think titleOnKeyUp() on edit-project.js would be necessary, I'm fine with seeing Task 13 or Milestone 3 on the metaboxes. As always, my pull requests are just suggestions and I will be completely fine having them rejected or modified.

Thanks,

@awijasa

**Comment by upstreamplugin** [comment]
Thanks @awijasa Looking forward to it! Speed is absolutely something we'd like to improve and yes - we're happy to make some tradeoffs.

**Comment by awijasa** [comment]
I just submitted a pull request that contains a CMB2 modification. Since CMB2 at its current state at UpStream may cause infinite loops, I think this mod will be worth it!
