### ISSUE TITLE
More flexible permissions

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#43]
Can we allow administrators to customize the permissions?

For example, one customer wants to allow users to create milestones via the front-end extension.

Another customer wants to make the tasks viewable by the public. At the moment, the lowest possible role is UpStream User, and that role has too many permissions for this use-case.

Another use-case would be UpStream itself. We could create a public list of tasks and bugs.

**Comment by upstreamplugin** [comment]
One request for permissions on viewing bugs and discussions:
https://wordpress.org/support/topic/why-clients-should-have-permission-to-view-discussion-and-project-bugs/#post-9576002

**Comment by deenison** [comment]
Not sure if this makes sense to be a new extension instead of a core feature. 
I mean, we definitely should (and will) revise all current offered permissions to make sure they're working and if there's any missing or that could be added. 

But the main goal of this issue, theoretically, couldn't be achieved by using third-party User Roles Editor plugins?

**Comment by upstreamplugin** [comment]
Yes, that's right. Plugins like Members are excellent and free. We can just provide compatibility with them.

**Comment by deenison** [comment]
Great! Thanks

**Comment by upstreamplugin** [comment]
Closed in favor of https://github.com/upstreamplugin/UpStream/issues/272
