### ISSUE TITLE
Allow users to create custom milestones for projects

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#662]
At the moment, we have a fixed set of milestones for all projects

Users should be able to customize their milestones

**Comment by stevejburge** [comment]
One vote for this from a customer today

**Comment by andergmartins** [comment]
This issue is the first step for the new architecture of data we are planning for UpStream. We will do it step-by-step starting from Milestones. We can convert the "static" list we have in the settings page to a custom post type. It should have default fields, but be customizable with custom fields. Should have backward compatibility with current projects, migrating the data.

As a start point, the new structure should allow creating milestones on each project, having a list in the main menu, as we have for tasks.

**Comment by andergmartins** [comment]
Closing this issue. Duplicates #281
