### ISSUE TITLE
Should Client Users be real WordPress users?

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#67]
It seems odd that:

1) All Client Users have the same password
2) They lack the ability to change their password, add avatars etc.

**Comment by deenison** [comment]
Thats a very good question. But double thumbs up to revamp this feature, imho. 
Apart from the potential security issues that come from having a single password per client and thus all of "his" users, 
I think it would definitely be better if Administrators were adding WordPress Users with a specific role, and only then associating whomever they want to one or multiple clients, instead of client-pseudo-users.
That would also help with making user permissions more flexible in future implementations.

**Comment by upstreamplugin** [comment]
@deenison Agreed. This is something we should tackle in July, probably

**Comment by deenison** [comment]
This feature will be shipped through [issue#85](https://github.com/upstreamplugin/UpStream/issues/85).
