### ISSUE TITLE
PHP error in Issues area

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#773]
Two reports of this:

Warning: array_merge(): Argument #2 is not an array in /home/public_html/wp-content/plugins/upstream/includes/class-up-counter.php on line 89

<img width="521" alt="Screen Shot 2019-05-13 at 11 08 39 AM" src="https://user-images.githubusercontent.com/3868028/57632377-8255ee00-756f-11e9-89ce-a16782d87c86.png">

**Comment by stevejburge** [comment]
@andergmartins One more report of this today

**Comment by stevejburge** [comment]
And another report from a potential customer

**Comment by stevejburge** [comment]
And another today

**Comment by sergeidevstar001** [comment]
I checked the problem, so I think it can be resolved by disabling opcache.
Disable method : https://stackoverflow.com/questions/21556437/disable-opcache-temporarily
![image](https://user-images.githubusercontent.com/39214560/58151093-31df3e80-7c9b-11e9-93cd-eb32d97b9ed3.png)

**Comment by sergeidevstar001** [comment]
Another solution : plugin directory / includes / class-up-counter.php -> line 89
Please change it to following code.
$items = array_merge((array)$items, (array)$dataSet);
Because array_merge need array params.

Or you can use 
$items = array_merge_recursive((array)$items, (array)$dataSet);
array_merge_recursive — Merge one or more arrays recursively

**Comment by stevejburge** [comment]
Solved in 1.24.2
