### ISSUE TITLE
Multiple Tags in Custom Fields don't save correctly

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#775]
- Create Tags
- Create a Custom Field of the "Tag" type
- The Tags won't save if more than one is added

<img width="649" alt="Screen Shot 2019-05-17 at 8 47 54 AM" src="https://user-images.githubusercontent.com/3868028/57929140-82f8c800-7880-11e9-911c-6f472a9d8c97.png">

**Comment by sergeidevstar001** [comment]
Hi @stevejburge 
I'm sorry, could you remove current message on upwork for me?
Upwork don't allow it.
You can send me invite on slack. my mail address is middlov@gmail.com

**Comment by sergeidevstar001** [comment]
Thanks

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
I didn't found problem yet on Custom Field plugin.
So I'm going to debug Custom Field plugin at weekend.
Thanks.

**Comment by sergeidevstar001** [comment]
Hi, @andergmartins 
It saves meta_key on database.
_upstream_project_activity
But there are many items saved and complex.
If possible, I'd like you to let me know about saving rule for me.

**Comment by andergmartins** [comment]
Hi @sergeidevstar001 
That is almost there... you are correct, it saves the data as metadata. But the metadata `_upstream_project_activity` is only for log of the activities.
I have tested and the Tags custom field is working for Milestones, Tasks, Bugs and Files, but not for Projects. 
The custom fields for Tasks, Bugs and Files are saved along with the tasks, bugs, and files metadata (on the same register, serialised). Milestone is an exception because I started refactoring it so each custom field has its own metadata register in the database.

As you said, and confirmed by my tests, the tags are being saved for projects as a metadata `tags`. So they are on the database.

The data is there, so the problem is in the JavaScript which requests the project's data to fill the popup fields using Ajax:

https://github.com/upstreamplugin/UpStream-Frontend-Edit/blob/master/assets/js/project.js#L578

Please, check these methods/files:

https://github.com/upstreamplugin/UpStream-Frontend-Edit/blob/master/includes/class-up-frontend-process.php#L577
https://github.com/upstreamplugin/UpStream-Frontend-Edit/blob/master/includes/class-up-frontend-process.php#L682

https://github.com/upstreamplugin/UpStream-Custom-Fields/blob/2da9357c77b250b2e0e85d44251a46a3e39c0203/CustomFields/Pages/Project.php#L1203

The problem is probably somewhere on those methods.

**Comment by sergeidevstar001** [comment]
hi, @andergmartins 
I got it, Thanks.

**Comment by sergeidevstar001** [comment]
Hi, @andergmartins 
Thanks for your help.
I found problem.
![image](https://user-images.githubusercontent.com/39214560/58976155-5db10700-87f9-11e9-997e-595f66d10783.png)
It saves for project, only didn't show correctly.

**Comment by sergeidevstar001** [comment]
Fixed

**Comment by stevejburge** [comment]
This seems to cause new problems.

After adding a Tags field, the frontend editing is broken

<img width="239" alt="Screen Shot 2019-06-28 at 12 15 33 PM" src="https://user-images.githubusercontent.com/3868028/60356238-7ea2ed00-999e-11e9-8dd6-f594a12f6f79.png">

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
I found problem, if it saves on admin panel, it works good, but if it saves on edit modal, it cause problem.
I will find solution.

**Comment by sergeidevstar001** [comment]
Fixed
