### ISSUE TITLE
Allow Start Date and End Date to be the same

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#782]
If a Task is only one day, why not allow the Start Date and End Date to be the same?

This might make added sense if we allow Time to be added to Dates.

**Comment by sergeidevstar001** [comment]
Fixed

**Comment by oraclerob** [comment]
Hi, can you tell me how this was fixed? I've fixed this as the actual issue is because the timezones in Wordpress aren't being used correctly. The issue doesn't have anything to do with timestamps.

**Comment by sergeidevstar001** [comment]
I compared start date and end date with string.
start date string == end date string -> return true;

**Comment by oraclerob** [comment]
Your solution is not correct and will still allow incorrect dates (past dates) to be valid. The solution is to correctly calculate the dates based on the Wordpress timezone settings this fixes the problem and enforces the validation.

**Comment by stevejburge** [comment]
Thanks @oraclerob and @sergeidevstar001 

@andergmartins Could you bring a 3rd pair of eyes to this?

**Comment by oraclerob** [comment]
The correct solution is here - you need to add a function to get the time offset and then display that when displaying the table data in class-up-view.php. Below is what I've done to fix this:

public static function getTimeZoneOffset() {
		$offset  = get_option( 'gmt_offset' );
		$sign    = $offset < 0 ? '-' : '+';
		$hours   = (int) $offset;
		$minutes = abs( ( $offset - (int) $offset ) * 60 );
                $offset  = sprintf( '%s%d%02d', $sign, abs( $hours ), $minutes );
                $calc_offset_seconds = $offset < 0 ? $offset * -1 * 60 : $offset * 60;
		return ( $calc_offset_seconds );
	}

This display like this:

$row['start_date']   = ! isset($row['start_date']) || ! is_numeric($row['start_date']) || $row['start_date'] < 0 ? 0 : (int)$row['start_date'] + self::getTimeZoneOffset();
$row['end_date']     = ! isset($row['end_date']) || ! is_numeric($row['end_date']) || $row['end_date'] < 0 ? 0 : (int)$row['end_date'] + self::getTimeZoneOffset() ;

**Comment by andergmartins** [comment]
@oraclerob thank you for contributing 👍 I'm reviewing the changes. But when you committed you reverted some other fixes we already have. I'm cleaning up the branch and moving your changes to another branch. 

Please, could you check these guidelines for contributing? https://github.com/upstreamplugin/UpStream/blob/development/CONTRIBUTING.md

We do appreciate any contribution and see users helping us make us a happy. But sometimes we need to discuss the changes, and if everyone commit to the development branch it becomes hard to organize and it will soon become a mess, with reverted changes, a lot of resets, and other issues.

Thanks

**Comment by stevejburge** [comment]
Sorry @oraclerob and @andergmartins. 100% my fault - I should have had more coffee this morning

**Comment by andergmartins** [comment]
@stevejburge sure, no problem! 👍

**Comment by andergmartins** [comment]
@sergeidevstar001 please, could you refer the commit you sent fixing this issue? Is it on another repository? If so, I think there is a chance we are probably talking about different issues here.

**Comment by andergmartins** [comment]
@oraclerob I have created the branch `issue-#782` and cleanup up the commits, leaving only the fix.
Please, could you fork the repository and use that branch as base for creating a pull request? I have some notes about the changes you are proposing.

**Comment by andergmartins** [comment]
@sergeidevstar001 and @oraclerob Please, could you fore a rebase on your local `development` branch? I reseted the branch but I think I should have reverted the target commits instead. Sorry about that. But I think if you rebase you will be ok.

**Comment by oraclerob** [comment]
Thanks Anderson,

 

Sorry I actually made an error – I’m using for the first time vscode to make the git commits and something has gone wrong with my local development branch and is not behaving as expected. I will actually make the changes directly to the correct branch via github rather than mess about with this until I have it sorted. My apologies.

 

Thanks

Rob.

**Comment by andergmartins** [comment]
@oraclerob sure, no problem we understand, thanks for your help. 

Btw, please clone our repository and the branch I created with your fix. Then you can send a pull request and we can continue the discussing the changes there.

**Comment by andergmartins** [comment]
@oraclerob I'm checking and there is a chance that is just a partial fix. You changed the getTasks method, but we are missing the same logic on the getBugs method. And the plugin probably get that fields (start_date and end_date) in other places that would require the same fix. Sorry, UpStream still have some structural issues and the code isn't much concise and consistent - we are working on that and you are certainly being helpful.

I agree with you, the timezone is still an issue on UpStream and add-ons. 
But maybe, before we include the timezone offset in the date output, we need to make sure the data are being saved as GMT in the database before applying the timezone to a date. Otherwise we won't have correct values among uses with different timezones.

**Comment by oraclerob** [comment]
Yes agree this is probably a partial fix. I still have one more related fix to go into the JavaScript for the frontend edit project. This must go in at the same time but it's very late here and I'll get to it tomorrow.




Regards,


Rob




Robert Mascaro


SCNet




e: rmascaro@scnet.com.au


o: +61(0) 8 6381 0001


w: http://www.scnet.com.au







On Tue, Jun 11, 2019 at 1:41 AM +0800, "Anderson Grüdtner Martins" <notifications@github.com> wrote:












@oraclerob I'm checking and there is a chance that is just a partial fix. You changed the getTasks method, but we are missing the same logic on the getBugs method. And the plugin probably get that fields (start_date and end_date) in other places that would require the same fix. Sorry, UpStream still have some structural issues and the code isn't much concise and consistent - we are working on that and you are certainly being helpful.


I agree with you, the timezone is still an issue on UpStream and add-ons.

But maybe, before we include the timezone offset in the date output, we need to make sure the data are being saved as GMT in the database before applying the timezone to a date. Otherwise we won't have correct values among uses with different timezones.

**Comment by andergmartins** [comment]
No problem, thanks. 
If it is a different issue, but related one, please, make sure to create/mention a new issue and respective branch 👍 Thanks!

**Comment by oraclerob** [comment]
@andergmartins  you’re right – these are partial fixes but necessary for my client who is using the Frontend heavily, especially Tasks. These timezone date issues are very serious and I would imagine that Upstream would give them top priority as incorrect dates on a project make the product unusable.

I’ve provided another Frontend fix for Bugs (#799) however there are still many issues with the Backend dates. I have not been able to work out how the Milestone dates are being rendered (front and back) at all, nor the Bugs (back end). To be honest it’s a bit of a mess  (and an extremely confusing approach) with many different ways and routines which don't make a lot of sense.

The good news is that all date timestamps appear to be GMT in  my testing which is what we want. The issues are that most of them are not being converted for display – especially in the Backend which needs further work.
