### ISSUE TITLE
Add option for support link url rather than email mailto link 

### ISSUE THREAD

**Issue by endurtech** [upstreamplugin/UpStream#81]
Some clients don't have a mail program installed or configured on their PCs. Thus the mailto link does nothing for them. I would love to have an option to link them to a contact form or knowledgebase support url rather than a mailto link. Sorry, I am new to GitHub. You all must now suffer the wrath of a newbie git user.

The below pull requests only address the bottom left sidebar contact link.

#80 #79 #78  

🥇

**Comment by deenison** [comment]
First of all, **thank you** for your interest and contributions on UpStream @endurtech, and second, there's absolutely nothing to be sorry for. We've all been on the wrath stage once :smile: Git is awesome thought.

Once your pull requests are reviewed and approved, they should be shipped on the next release.

However, a better approach to contributing through pull requests would be to group all changes/commits related to a given issue into a single PR (pull request), instead of open one per commit.

Taking your contribution as example: it seems that you broke the issue itself - described on your report above - into smaller parts, and by that, created individual branches into your fork to tackle each one of those pieces.
The idea is **great** and you're in the right track, BUT things can get out of control really quick if we end up having to deal with a more complex issue which might demands tons and tons of commits (that would leave us with the same ton of branches and pull requests).

So, in this case, since all three commits are tackling the very same problem (and GitHub Issue), it would be better and more practical to have a single branch (usually named referencing what we are doing there or the GitHub Issue #, i.e. `patch-81`) with three commits and after that a single PR instead of three branches with one commit only and three PRs.
